mode: dualtower
vlm:
  vit_hidden_dim: 384
  vit_inter_dim: 512
  vit_patch_size: 16
  vit_img_size: 256
  vit_n_heads: 6
  vit_dropout: 0.0
  vit_n_blocks: 2
  vit_ln_eps: 1.0e-06
  vit_cls_flag: false
  vit_model_type: google/siglip2-base-patch16-512
  lm_hidden_dim: 384
  lm_inter_dim: 512
  lm_rms_eps: 1.0e-05
  lm_re_base: 100000
  lm_max_position_embeddings: 2048
  lm_base_vocab_size: 49152
  extra_token_amount: 66
  lm_vocab_size: 49218
  lm_n_heads: 8
  lm_n_kv_heads: 4
  lm_dropout: 0.0
  lm_n_blocks: 4
  lm_attn_scaling: 1.0
  lm_max_length: 512
  lm_use_tokens: false
  lm_tie_weights: true
  lm_model_type: HuggingFaceTB/SmolLM2-135M-Instruct
  lm_tokenizer: HuggingFaceTB/SmolLM2-135M-Instruct
  lm_chat_template: '{% for message in messages %}{{''<|im_start|>'' + message[''role'']
    + ''

    '' + message[''content''] + ''<|im_end|>'' + ''

    ''}}{% endfor %}{% if add_generation_prompt %}{{ ''<|im_start|>assistant

    '' }}{% endif %}'
  mp_pixel_shuffle_factor: 4
  mp_image_token_length: 16
  max_img_size: 1024
  resize_to_max_side_len: false
  vlm_extra_tokens:
    image_token: <|image|>
    global_image_token: <|global_image|>
    r1c1: <row_1_col_1>
    r1c2: <row_1_col_2>
    r1c3: <row_1_col_3>
    r1c4: <row_1_col_4>
    r1c5: <row_1_col_5>
    r1c6: <row_1_col_6>
    r1c7: <row_1_col_7>
    r1c8: <row_1_col_8>
    r2c1: <row_2_col_1>
    r2c2: <row_2_col_2>
    r2c3: <row_2_col_3>
    r2c4: <row_2_col_4>
    r2c5: <row_2_col_5>
    r2c6: <row_2_col_6>
    r2c7: <row_2_col_7>
    r2c8: <row_2_col_8>
    r3c1: <row_3_col_1>
    r3c2: <row_3_col_2>
    r3c3: <row_3_col_3>
    r3c4: <row_3_col_4>
    r3c5: <row_3_col_5>
    r3c6: <row_3_col_6>
    r3c7: <row_3_col_7>
    r3c8: <row_3_col_8>
    r4c1: <row_4_col_1>
    r4c2: <row_4_col_2>
    r4c3: <row_4_col_3>
    r4c4: <row_4_col_4>
    r4c5: <row_4_col_5>
    r4c6: <row_4_col_6>
    r4c7: <row_4_col_7>
    r4c8: <row_4_col_8>
    r5c1: <row_5_col_1>
    r5c2: <row_5_col_2>
    r5c3: <row_5_col_3>
    r5c4: <row_5_col_4>
    r5c5: <row_5_col_5>
    r5c6: <row_5_col_6>
    r5c7: <row_5_col_7>
    r5c8: <row_5_col_8>
    r6c1: <row_6_col_1>
    r6c2: <row_6_col_2>
    r6c3: <row_6_col_3>
    r6c4: <row_6_col_4>
    r6c5: <row_6_col_5>
    r6c6: <row_6_col_6>
    r6c7: <row_6_col_7>
    r6c8: <row_6_col_8>
    r7c1: <row_7_col_1>
    r7c2: <row_7_col_2>
    r7c3: <row_7_col_3>
    r7c4: <row_7_col_4>
    r7c5: <row_7_col_5>
    r7c6: <row_7_col_6>
    r7c7: <row_7_col_7>
    r7c8: <row_7_col_8>
    r8c1: <row_8_col_1>
    r8c2: <row_8_col_2>
    r8c3: <row_8_col_3>
    r8c4: <row_8_col_4>
    r8c5: <row_8_col_5>
    r8c6: <row_8_col_6>
    r8c7: <row_8_col_7>
    r8c8: <row_8_col_8>
  vlm_load_backbone_weights: false
  vlm_checkpoint_path: lusxvr/nanoVLM-230M-8k
  hf_repo_name: nanoVLM
  left_tower_mask_mode: visual_only
  activation_checkpointing: false
  activation_checkpointing_mode: "regular"

train:
  lr_mp: 0.0005
  lr_vision_backbone: 0
  lr_language_backbone: 0.0001
  lr_left_tower: null
  lr_right_tower: 0.0
  val_size: 50000
  batch_size: 4
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  eval_in_epochs: true
  eval_interval: 100
  checkpoint_interval: 100
  stats_log_interval: 20
  max_training_steps: 2
  max_images_per_example: 1
  max_images_per_knapsack: 8
  max_sample_length: 512
  use_packing: true
  compile: false
  resume_from_vlm_checkpoint: true
  train_dataset_path: patrickamadeus/the_cauldron
  train_dataset_name:
  - sample_1pct
  train_split: train
  val_split: validation
  stream_dataset: false
  relevance_min_rating: 1
  image_correspondence_min_rating: 1
  visual_dependency_min_rating: 1
  formatting_min_rating: 1
  wandb_entity: patrickirawan-mbzuai
  wandb_project: "dualtower-preflight"
  wandb_run_name_prefix: "preflight-ckpt"
  log_wandb: false
  use_lmms_eval: false
  lmms_eval_tasks: mmstar,mmmu_val,ocrbench,textvqa_val,docvqa_val,scienceqa,mme,infovqa_val,chartqa
  lmms_eval_limit: null
  lmms_eval_batch_size: 64
  push_checkpoints_to_hub: false
  checkpoint_repo_pattern: patrickamadeus/dt8k1img-ref-step-{i}
  hf_private: false
  push_final_model_to_hub: false
